### ISSUE TITLE
artist tags below pixiv work thumbnail became ugly

### ISSUE THREAD

**Issue by hdk5** [evazion/translate-pixiv-tags#95]
https://github.com/evazion/translate-pixiv-tags/blob/ca2434abe59dcbccb561ff9e1baf66fb045a6c0b/translate-pixiv-tags.user.js#L3367-L3390

I believe this is caused by the recent pixiv html layout change that broke some other scripts too.
IIRC, the translated tags were used to be displayed under the original artists' name.
Now they are displayed to the side of it, so when either is too long, the original artist name becomes obstructed by the translated tag.

**Comment by hdk5** [comment]
It is broken again after https://github.com/evazion/translate-pixiv-tags/commit/ce0764ac0ca3c4251521ad37ab14c36dfd0f2ccd

**Comment by 7nik** [comment]
Looks ok to me

**Comment by hdk5** [comment]
https://www.pixiv.net/bookmark_new_illust.php

907a840a5818a9d1c2247d3b180e0f32d23dc545:
![Image](https://github.com/user-attachments/assets/b557e710-abc3-4d31-b78e-aeec2227f9b1)

3e7fc424be262d7e1896a544be89d1e6c5a34572:
![Image](https://github.com/user-attachments/assets/c2b91bd6-7d06-44f9-ac56-e0d565c925ea)

**Comment by 7nik** [comment]
<img width="102" alt="Image" src="https://github.com/user-attachments/assets/fbd021ea-8efe-4505-9d90-c649f64b90ba" />
on the recent 20250417210213 in both FF in Chromium

The only breakable thing in that commit is that I started to use there is [nested selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting/Using_CSS_nesting) which is [supported by all browsers](https://caniuse.com/css-nesting) since around Dec 2023

**Comment by hdk5** [comment]
Checked on Edge, still appears wrong

**Comment by 7nik** [comment]
So, for now, my only guess is pixiv again does the A/B thing, and we are in different groups.
